### ISSUE TITLE
Not work on Windows 7

### ISSUE THREAD

**Issue by lesydat** [hex7c0/mkdir-recursive#5]
I use mkdirSync on Windows 7, this error happen: Error: ENOENT: no such file or directory

**Comment by Syndesi** [comment]
Happens to me too:
```sh
fs.js:110
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\soere\Documents\Programme\Backup\backup\backup\DESKTOP-965L2GP\2018.05.05_19.58.10_full\'
    at Object.fs.mkdirSync (fs.js:840:3)
    at mkdirSyncRecursive (C:\Users\soere\Documents\Programme\Backup\node_modules\mkdir-recursive\index.js:199:16)
    at mkdirSyncRecursive (C:\Users\soere\Documents\Programme\Backup\node_modules\mkdir-recursive\index.js:197:12)
    at mkdirSyncRecursive (C:\Users\soere\Documents\Programme\Backup\node_modules\mkdir-recursive\index.js:197:12)
    at mkdirSyncRecursive (C:\Users\soere\Documents\Programme\Backup\node_modules\mkdir-recursive\index.js:197:12)
    at mkdirSyncRecursive (C:\Users\soere\Documents\Programme\Backup\node_modules\mkdir-recursive\index.js:197:12)
    at mkdirSyncRecursive (C:\Users\soere\Documents\Programme\Backup\node_modules\mkdir-recursive\index.js:197:12)
    at Object.mkdirSync (C:\Users\soere\Documents\Programme\Backup\node_modules\mkdir-recursive\index.js:82:10)
    at Backup.createBackupFolder (C:\Users\soere\Documents\Programme\Backup\src\index.js:33:8)
    at Backup.createFullBackup (C:\Users\soere\Documents\Programme\Backup\src\index.js:24:21)
error Command failed with exit code 1.
```

(Node.js 10.0.0, npm 5.6.0, Windows 10)

**Comment by ajsnyde** [comment]
Same
{ Error: ENOENT: no such file or directory, mkdir 'C:\Users\MuhName\fhir-schema-generator\lib\src\foo\bar\1'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\Users\\MuhName\\fhir-schema-generator\\lib\\src\\foo\\bar\\1' }

**Comment by Itayp1** [comment]
same
